### ISSUE TITLE
Trouble implementing oauth authorization via GET

### ISSUE THREAD

**Issue by drakezhard** [mattrepl/clj-oauth#41]
This is my implementation of the Khan Academy Api. Acording to https://github.com/Khan/khan-api/tree/master/examples/php_test_client the signature needs to have no authorization url because Khan Academy skips that step. 

    (ns khan.api
      (:require [oauth.client :as oauth]
                [oauth.signature :as sig]
                [clj-http.client :as http]))

    (def consumer-key "B9nyR6w6NbLRzbQr")
    (def consumer-secret "pUQFGKGebZVhEuCA")

    (def consumer (oauth/make-consumer consumer-key
                                       consumer-secret
                                       "https://www.khanacademy.org/api/auth/request_token"
                                       "https://www.khanacademy.org/api/auth/access_token"
                                       "https://www.khanacademy.org/api/auth/authorization"
                                       :hmac-sha1))

    (def noauth   (oauth/make-consumer consumer-key
                                       consumer-secret
                                       "https://www.khanacademy.org/api/auth/request_token"
                                       ""
                                       "https://www.khanacademy.org/api/auth/authorization"
                                       :hmac-sha1))

    (defn build-oauth-token-request
      "Used to build actual OAuth request."
      ([consumer uri unsigned-oauth-params]
       (let [signature (sig/sign consumer
                                 (sig/base-string "GET" uri unsigned-oauth-params))
             oauth-params (assoc unsigned-oauth-params :oauth_signature signature)]
         (oauth/build-request oauth-params))))

    (defn request-token
      "Fetch request token for the consumer."
      ([consumer noauth callback-uri]
       (let [unsigned-params (-> (sig/oauth-params consumer
                                                   (sig/rand-str 30)
                                                   (sig/msecs->secs (System/currentTimeMillis)))
                                 (assoc :oauth_callback callback-uri))]
         {:status 200
          :headers {"Content-Type" "text/html"} 
          :body (:body (http/get (:request-uri consumer)
                                 (build-oauth-token-request noauth
                                                            (:request-uri consumer)
                                                            unsigned-params)))})))

And this is the server that hosts it. I'm having trouble with redirecting to the login callback, I have no idea why khan academy sends me to the default callback. My (probably incorrect) understanding is that upon successful authentication and having provided a callback, the khan academy server sends a GET or POST request to the callback server. I'm using compojure destructuring on "/login/:params" and I was expecting the webpage to print the query params of the GET request. I'm clueless right now.

    (ns khan.web
      (:require [compojure.core :refer [defroutes GET PUT POST DELETE ANY]]
                [compojure.handler :refer [site]]
                [compojure.route :as route]
                [clojure.java.io :as io]
                [ring.adapter.jetty :as jetty]
                [environ.core :refer [env]]
                [khan.api :as khan]))

    (defn khan-api []
      (khan/request-token khan/consumer khan/noauth "http://localhost:5000/login/"))

    (defroutes app
      (GET "/" []
           (khan-api))
      (POST "/login/:params" [params]
           (str params))
      (ANY "*" []
           (route/not-found (slurp (io/resource "404.html")))))

    (defn -main [& [port]]
      (let [port (Integer. (or port (env :port) 5000))]
        (jetty/run-jetty (site #'app) {:port port :join? false})))

**Comment by mattrepl** [comment]
Have you checked that the request map result from `build-oauth-token-request` contains the `oauth_callback` parameter? I see the Khan Academy documentation states they respect the auth_callback param, but I'd also recommend looking at whatever "developer profile" page they may have which may let you specify a default callback to use for your application. Twitter used to (still does?) do that.

I'm not sure why you need the `noauth` consumer without the access URI. That URI is only used when requesting the access token and doesn't affect other requests (e.g., obtaining a request token).

**Comment by drakezhard** [comment]
I removed the noauth consumer. They don't have a developer profile. I have a few ideas I'm going to study their php client, it has the :oauth_callback param but it's written in php and it's really ugly. Their python client is of no use because it requires you to copy the request-token manually from the url. 

I cleaned up the request-token to return a ring response map that opens a new browser tab. But still no callback.

    (defn request-token
      "Fetch request token for the consumer."
      ([consumer callback-uri]
       (let [unsigned-params (-> (sig/oauth-params consumer
                                                   (sig/rand-str 30)
                                                   (sig/msecs->secs (System/currentTimeMillis)))
                                 (assoc :oauth_callback callback-uri))
             request (http/get (:request-uri consumer)                             
                               (build-oauth-token-request consumer
                                                          (:request-uri consumer)
                                                          unsigned-params))]
         {:status 200
          :content {"Content-Type" "text/html"}
          :body (str "<a href=" (nth (:trace-redirects request) 1) ">Login</a>")})))

**Comment by drakezhard** [comment]
This is from the ka_academy.php file:
    /*
     * Initial login handler (accessed by specifying login=1). Unlike most OAuth
     * APIs, the KA API skips the "authorize" step, and instead guides the user
     * through the login process directly from /api/auth/request_token . That
     * endpoint redirects to a login page, which redirects back to a
     * loginCallback of our choosing. Since this is a different flow from what
     * the OAuth library expects, we need to have oauth-php sign the request
     * without submitting it (since it's expecting to directly get a token
     * back), then redirect the user to the resulting URL.
     */

**Comment by drakezhard** [comment]
I finally got it.

Here instead of creating an authorization header to issue a get request, I just used your sig/url-form-encode function.

    (defn build-oauth-token-request
      "Used to build actual OAuth request."
      ([consumer uri unsigned-oauth-params]
       (let [signature (sig/sign consumer
                                 (sig/base-string "GET" uri unsigned-oauth-params))
             oauth-params (assoc unsigned-oauth-params :oauth_signature signature)]
         (sig/url-form-encode oauth-params))))

And here I made a html link to the url constructed with the token params and lo an behold the server redirected me.

    (defn request-token-handler
      "Fetch request token for the consumer."
      ([consumer callback-uri]
       (let [unsigned-params (-> (sig/oauth-params consumer
                                                   (sig/rand-str 30)
                                                   (sig/msecs->secs (System/currentTimeMillis)))
                                 (assoc :oauth_callback callback-uri))
             request-params  (build-oauth-token-request consumer                                  
                                                        (:request-uri consumer)                                    
                                                        unsigned-params)]
         {:status 200
          :headers {"Content-Type" "text/html"}
          :body (str "<a href=\""(:request-uri consumer) "?" request-params "\">Login</a>")})))

 Now it's just a matter of destructuring the query string, Compojure will take care of it. Thanks.
