### ISSUE TITLE
Update bouncycastle version to 1.5.4

### ISSUE THREAD

**Issue by prateekbhatt** [mattrepl/clj-oauth#45]
Hi, Could you update the bouncycastle version ? Currently it is set at 1.5.0 , however, some libraries like Buddy (for authentication) require the 1.5.4 version, and the 1.5.0 version here is breaking those.

**Comment by mattrepl** [comment]
Thanks for the note. I just pushed clj-http 1.5.4 to clojars with updated dependencies for bouncycastle (1.5.4), Clojure (1.7), and clj-http (2.0.1).
