### ISSUE TITLE
Code 32: Could not authenticate you

### ISSUE THREAD

**Issue by fommil** [mattrepl/clj-oauth#49]
I create a `config.clj` containing my details, with this structure

```clojure
(def ^:const +twitter_consumer_key+ "...")
(def ^:const +twitter_consumer_secret+ "...")
(def ^:const +twitter_access_token+ "")
(def ^:const +twitter_access_token_secret+ "")
```

and then run this code

```clojure
(ns fommil.teflon.core
  (:require
   [oauth.client :as oauth]
   [clj-http.client :as http]))

(load-file "config.clj")

(def consumer (oauth/make-consumer
               +twitter_consumer_key+
               +twitter_consumer_secret+
               "https://api.twitter.com/oauth/request_token"
               "https://api.twitter.com/oauth/access_token"
               "https://api.twitter.com/oauth/authorize"
               :hmac-sha1))

(def credentials (oauth/credentials
                  consumer
                  +twitter_access_token+
                  +twitter_access_token_secret+
                  :get
                  "https://api.twitter.com/1.1/statuses/user_timeline.json"
                  {:screen_name "fommil"}))

(http/get "https://api.twitter.com/1.1/statuses/user_timeline.json"
          {:query-params credentials})
```

but I get

```
 clj-http: status 401 {:status 401, :headers {"server" "tsa_f", "content-type" "application/json; charset=utf-8", "content-length" "89", "x-connection-hash" "<obfuscated>", "strict-transport-security" "max-age=631138519", "connection" "close", "x-response-time" "106", "set-cookie" "guest_id=<obfuscated>; Domain=.twitter.com; Path=/; Expires=Mon, 19-Mar-2018 17:06:28 UTC", "date" "Sat, 19 Mar 2016 17:06:28 GMT"}, :body "{\"errors\":[{\"code\":32,\"message\":\"Could not authenticate you.\"}]}", :request-time 452, :trace-redirects ["https://api.twitter.com/1.1/statuses/update.json"], :orig-content-encoding "gzip"}
```

i.e. code 32 "Could not authenticate you".

I can run a similar command, as per the twitter OAuth tool's `curl` example, using the same tokens, and everything works as expected.

Is this a bug or am I doing it wrong?

I've seen that similar errors are reported in other OAuth libraries for other languages https://twittercommunity.com/t/errors-message-could-not-authenticate-you-code-32/1223

**Comment by fommil** [comment]
needed to `(merge credentials { params } )`

**Comment by fommil** [comment]
actually, I'm reopening this because it is a documentation error. The README has `http` (which is not supported) and doesn't `merge` the credentials with the user payload into `:query-params`.

**Comment by mattrepl** [comment]
Good catch, will update the docs. Thanks for reporting!

**Comment by fommil** [comment]
OAuth itself really stung me yesterday, it was really hard to find out about the principles behind it. It would be really fantastic if you could explain OAuth in simple terms, as it can be very confusing.

As a developer I am able to create my own quadruple of `(app token, app secret, access token, access secret)` which gets development moving... it's only afterwards that one needs to worry about implementing `(app token, app secret) => (access token, access secret)` lookup and generating the URL to show to users the first time so that the lookup actually works. I guess the lookup and URL generation both require an HTTP implementation to be provided.

In terms of the lookup, I found that `oauth-request-token` from https://github.com/r0man/oauth-clj is pretty nice (hid all the internal details about verifiers), but I don't think there is any particular need for that library to exist anymore.

**Comment by mattrepl** [comment]
Fixed.

**Comment by fommil** [comment]
not so fast, you have your brackets the wrong way round :smile:

**Comment by mattrepl** [comment]
Yeesh! I've become too dependent on paredit. =) Fixed.
