### ISSUE TITLE
inconsistent licence

### ISSUE THREAD

**Issue by fommil** [mattrepl/clj-oauth#50]
Your LICENSE is Simplified BSD, but your project file is Eclipse Public License.

Can you please clarify which licence you are releasing this software under? I will assume dual licence unless corrected :smile: (and I choose Simplified BSD).

**Comment by mattrepl** [comment]
Yes, simplified BSD. Will update project file, thanks!

**Comment by fommil** [comment]
the reason I ask is because I don't want the dependency on `clj-http` so I'm taking just the bits I need. I've been told that https://github.com/jcf/oauth/ will be the future, if you're not already it would be great if you could pool your resources and perhaps turn it into `clj-oauth` v2.

**Comment by mattrepl** [comment]
There's no reason for a dependency on clj-http. That was a requirement for a project this library was written for, but it should be changed. The clj-oauth functions should just return the params and headers for requests and let the user choose their own HTTP client. It looks like jcf's oauth is doing something similar to that. Out of curiosity, why use clj-oauth instead of jcf's oauth?

If you do end up updating clj-oauth to remove the clj-http dependency, I'll gladly accept a pull request.

**Comment by fommil** [comment]
I don't think I can remove `clj-http` without breaking your API but if you're OK doing that I might be able to put something together.

jcf's repo is very new and is "not yet released" according to the notes. Maybe something for the future.

**Comment by mattrepl** [comment]
Yes, I think the API will have to change, and that's OK. We'll make it a major version bump.

It may be possible to also provide "authentication workflow" function(s) which would require the user to provide functions for making and parsing HTTP requests and responses. This would help prevent the user from dealing directly with the OAuth workflow.

**Comment by fommil** [comment]
it's unlikely that I'll get round to this because I've just given myself the weekend to learn clojure and then I'm back to some pretty big commitments in Scala land (plus my wife has just informed me that the laptop has to go away :blush: )

**Comment by mattrepl** [comment]
Hah, no worries, it's something that's needed to be done for awhile. But with jcf's oauth lib, maybe it's time to deprecate clj-oauth in the near future.

Fixed the license mismatch in project.clj. Feel free to open up another issue if anything else comes up or you want to tinker with the clj-http removal.

**Comment by fommil** [comment]
I think it would be best if jcf's library becomes clj-oauth v2 actually, I really hate to see fragmentation.
